[[mgr.prepend_keymap]]
   on   = "<C-y>"
   run  = ["plugin wl-clipboard"]
   desc = "yank files in clipboard"

[[mgr.prepend_keymap]]
   on   = [ "c" ]
   run  = "plugin chmod"
   desc = "Chmod on selected files"


